name: apiverve_colorpalette
description: Color Palette is a powerful tool for generating harmonious color palettes. Generate color schemes (mono, contrast, triade, tetrade, analogic) with accessibility data, CSS exports, and palette images.
version: 1.1.14
homepage: https://apiverve.com/marketplace/colorpalette?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/colorpalette-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
